using System.Text;
using System.Text.RegularExpressions;

namespace VCenterDeployGUI
{
    public class EnvFileManager
    {
        public Dictionary<string, string> LoadEnvFile(string filePath)
        {
            var envData = new Dictionary<string, string>();
            
            if (!File.Exists(filePath))
                return envData;

            var lines = File.ReadAllLines(filePath);
            
            foreach (var line in lines)
            {
                var trimmedLine = line.Trim();
                
                // Skip empty lines and comments
                if (string.IsNullOrEmpty(trimmedLine) || trimmedLine.StartsWith("#"))
                    continue;

                // Parse key=value pairs
                var match = Regex.Match(trimmedLine, @"^([^=]+)=(.*)$");
                if (match.Success)
                {
                    var key = match.Groups[1].Value.Trim();
                    var value = match.Groups[2].Value.Trim();
                    
                    // Remove quotes if present
                    if ((value.StartsWith("\"") && value.EndsWith("\"")) ||
                        (value.StartsWith("'") && value.EndsWith("'")))
                    {
                        value = value.Substring(1, value.Length - 2);
                    }
                    
                    envData[key] = value;
                }
            }

            return envData;
        }

        public Dictionary<string, string> LoadEnvExample(string filePath)
        {
            var envData = new Dictionary<string, string>();
            
            if (!File.Exists(filePath))
                return envData;

            var lines = File.ReadAllLines(filePath);
            
            foreach (var line in lines)
            {
                var trimmedLine = line.Trim();
                
                // Skip empty lines and comments but process them for structure
                if (string.IsNullOrEmpty(trimmedLine) || trimmedLine.StartsWith("#"))
                    continue;

                // Parse key=value pairs, keeping default values
                var match = Regex.Match(trimmedLine, @"^([^=]+)=(.*)$");
                if (match.Success)
                {
                    var key = match.Groups[1].Value.Trim();
                    var value = match.Groups[2].Value.Trim();
                    
                    // Remove quotes if present
                    if ((value.StartsWith("\"") && value.EndsWith("\"")) ||
                        (value.StartsWith("'") && value.EndsWith("'")))
                    {
                        value = value.Substring(1, value.Length - 2);
                    }
                    
                    // For example files, keep defaults as placeholders
                    envData[key] = value;
                }
            }

            return envData;
        }

        public void SaveEnvFile(string filePath, Dictionary<string, string> envData)
        {
            var sb = new StringBuilder();
            sb.AppendLine("# vCenter Deployment Configuration");
            sb.AppendLine("# Generated by vCenter Deployment GUI");
            sb.AppendLine($"# Generated on: {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
            sb.AppendLine();

            // Group related settings
            var groups = new Dictionary<string, List<string>>
            {
                ["General"] = new() { "VM_NAME" },
                ["Paths"] = new() { "VCSA_CLI_PATH", "VCSA_HOST" },
                ["vCenter Credentials"] = new() { "VC_PASSWORD", "VCSA_ROOT_PASSWORD" },
                ["ESXi Host"] = new() { "ESXI_HOST", "ESXI_USER", "ESXI_PASSWORD" },
                ["Time Settings"] = new() { "NTP_SERVERS" },
                ["Deployment Options"] = new() { "DEPLOYMENT_NETWORK", "DATASTORE", "THIN_DISK_MODE", "DEPLOYMENT_OPTION" },
                ["Network Configuration"] = new() { "IP_ADDRESS", "DNS_SERVERS", "NETWORK_PREFIX", "GATEWAY" },
                ["SSO Configuration"] = new() { "SSO_DOMAIN" },
                ["Other Settings"] = new() { "CEIP_SETTINGS" }
            };

            foreach (var group in groups)
            {
                sb.AppendLine($"# {group.Key}");
                
                foreach (var key in group.Value)
                {
                    if (envData.ContainsKey(key))
                    {
                        var value = envData[key];
                        
                        // Quote values that contain spaces or special characters
                        if (value.Contains(' ') || value.Contains('#') || value.Contains('='))
                        {
                            value = $"\"{value}\"";
                        }
                        
                        sb.AppendLine($"{key}={value}");
                    }
                }
                sb.AppendLine();
            }

            // Add any remaining keys not in groups
            var processedKeys = groups.SelectMany(g => g.Value).ToHashSet();
            var remainingKeys = envData.Keys.Where(k => !processedKeys.Contains(k)).ToList();
            
            if (remainingKeys.Any())
            {
                sb.AppendLine("# Additional Settings");
                foreach (var key in remainingKeys)
                {
                    var value = envData[key];
                    if (value.Contains(' ') || value.Contains('#') || value.Contains('='))
                    {
                        value = $"\"{value}\"";
                    }
                    sb.AppendLine($"{key}={value}");
                }
            }

            File.WriteAllText(filePath, sb.ToString(), Encoding.UTF8);
        }

        public Dictionary<string, ConfigField> GetConfigurationFields()
        {
            return new Dictionary<string, ConfigField>
            {
                ["VM_NAME"] = new ConfigField 
                { 
                    DisplayName = "VM Name", 
                    Description = "Name for the vCenter VM", 
                    IsRequired = true,
                    ValidationPattern = @"^[a-zA-Z0-9_-]+$"
                },
                ["VCSA_CLI_PATH"] = new ConfigField 
                { 
                    DisplayName = "VCSA CLI Path", 
                    Description = "Path to vcsa-deploy.exe from mounted vCenter ISO", 
                    IsRequired = true,
                    IsFilePath = true,
                    DefaultValue = "[driveletter]:\\vcsa-cli-installer\\win32\\vcsa-deploy.exe"
                },
                ["VCSA_HOST"] = new ConfigField 
                { 
                    DisplayName = "vCenter FQDN", 
                    Description = "Fully qualified domain name for vCenter", 
                    IsRequired = true,
                    ValidationPattern = @"^[a-zA-Z0-9.-]+$"
                },
                ["VC_PASSWORD"] = new ConfigField 
                { 
                    DisplayName = "vCenter SSO Password", 
                    Description = "Password for vCenter Single Sign-On", 
                    IsRequired = true,
                    IsPassword = true
                },
                ["VCSA_ROOT_PASSWORD"] = new ConfigField 
                { 
                    DisplayName = "vCenter Root Password", 
                    Description = "Root password for vCenter appliance", 
                    IsRequired = true,
                    IsPassword = true
                },
                ["ESXI_HOST"] = new ConfigField 
                { 
                    DisplayName = "ESXi Host", 
                    Description = "IP address or FQDN of ESXi host", 
                    IsRequired = true,
                    ValidationPattern = @"^[a-zA-Z0-9.-]+$"
                },
                ["ESXI_USER"] = new ConfigField 
                { 
                    DisplayName = "ESXi Username", 
                    Description = "Username for ESXi host (typically 'root')", 
                    IsRequired = true,
                    DefaultValue = "root"
                },
                ["ESXI_PASSWORD"] = new ConfigField 
                { 
                    DisplayName = "ESXi Password", 
                    Description = "Password for ESXi host", 
                    IsRequired = true,
                    IsPassword = true
                },
                ["NTP_SERVERS"] = new ConfigField 
                { 
                    DisplayName = "NTP Servers", 
                    Description = "NTP servers (comma-separated)", 
                    DefaultValue = "pool.ntp.org"
                },
                ["DEPLOYMENT_NETWORK"] = new ConfigField 
                { 
                    DisplayName = "Deployment Network", 
                    Description = "ESXi port group for deployment", 
                    DefaultValue = "VM Network"
                },
                ["DATASTORE"] = new ConfigField 
                { 
                    DisplayName = "Datastore", 
                    Description = "ESXi datastore name", 
                    IsRequired = true
                },
                ["THIN_DISK_MODE"] = new ConfigField 
                { 
                    DisplayName = "Thin Disk Mode", 
                    Description = "Use thin provisioning for disks", 
                    IsBoolean = true,
                    DefaultValue = "false"
                },
                ["DEPLOYMENT_OPTION"] = new ConfigField 
                { 
                    DisplayName = "Deployment Size", 
                    Description = "vCenter appliance size (tiny, small, medium, large, xlarge)", 
                    IsDropdown = true,
                    DropdownOptions = new[] { "tiny", "small", "medium", "large", "xlarge" },
                    DefaultValue = "small"
                },
                ["IP_ADDRESS"] = new ConfigField 
                { 
                    DisplayName = "IP Address", 
                    Description = "Static IP address for vCenter", 
                    IsRequired = true,
                    ValidationPattern = @"^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$"
                },
                ["DNS_SERVERS"] = new ConfigField 
                { 
                    DisplayName = "DNS Servers", 
                    Description = "DNS servers (comma-separated)", 
                    IsRequired = true
                },
                ["NETWORK_PREFIX"] = new ConfigField 
                { 
                    DisplayName = "Network Prefix", 
                    Description = "Subnet mask prefix (e.g., 24)", 
                    IsRequired = true,
                    ValidationPattern = @"^(?:[1-9]|[12][0-9]|3[0-2])$"
                },
                ["GATEWAY"] = new ConfigField 
                { 
                    DisplayName = "Gateway", 
                    Description = "Default gateway IP address", 
                    IsRequired = true,
                    ValidationPattern = @"^(?:(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(?:25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$"
                },
                ["SSO_DOMAIN"] = new ConfigField 
                { 
                    DisplayName = "SSO Domain", 
                    Description = "Single Sign-On domain", 
                    DefaultValue = "vsphere.local"
                },
                ["CEIP_SETTINGS"] = new ConfigField 
                { 
                    DisplayName = "CEIP Settings", 
                    Description = "Customer Experience Improvement Program participation", 
                    IsBoolean = true,
                    DefaultValue = "false"
                }
            };
        }
    }

    public class ConfigField
    {
        public string DisplayName { get; set; } = "";
        public string Description { get; set; } = "";
        public string DefaultValue { get; set; } = "";
        public bool IsRequired { get; set; }
        public bool IsPassword { get; set; }
        public bool IsBoolean { get; set; }
        public bool IsDropdown { get; set; }
        public bool IsFilePath { get; set; }
        public string[]? DropdownOptions { get; set; }
        public string? ValidationPattern { get; set; }
    }
}